### ISSUE TITLE
Auto update error in the last update push

### ISSUE THREAD

**Issue by ArMaTeC** [mstinaff/PMS_Updater#64]
Updates are failing with the following error

Using URL https://plex.tv/api/downloads/5.json
Searching https://plex.tv/api/downloads/5.json for the FreeBSD download URL .....fetch: https://plex.tv/api/downloads/5.json?channel=plexpass&X-Plex-Token=<Removed>: No address record
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/usr/local/share/plexmediaserver-plexpass/Resources/Python/python27.zip/json/__init__.py", line 291, in load
File "/usr/local/share/plexmediaserver-plexpass/Resources/Python/python27.zip/json/__init__.py", line 339, in loads
File "/usr/local/share/plexmediaserver-plexpass/Resources/Python/python27.zip/json/decoder.py", line 364, in decode
File "/usr/local/share/plexmediaserver-plexpass/Resources/Python/python27.zip/json/decoder.py", line 382, in raw_decode
ValueError: No JSON object could be decoded
Could not find a FreeBSD download link on page https://plex.tv/api/downloads/5.json?channel=plexpass&X-Plex-Token=<Removed>
Command: /bin/sh /usr/local/PMS_Updater/PMS_Updater.sh -v -a failed!

**Comment by MAGICCC** [comment]
Which Plex version are you using at the moment?
Also are you sure that you use the latest script?

**Comment by ArMaTeC** [comment]
Seams to have auto corrected its self last night as no errors now and it updated
